[project]
name = 'community_waste_collection'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = [
  "SP3FBR2AGK7NZX1M4YXYRSBNPK7EDD1XT31X7FYYP.sip-010-trait-ft-standard"
]
[contracts.community_waste]
path = 'contracts/community_waste.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
